apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: h8ph9dm91-python-gitops
  description: This is GitOps manifest for h8ph9dm91-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: h8ph9dm91-python
    janus-idp.io/tekton: h8ph9dm91-python 
    backstage.io/kubernetes-id: h8ph9dm91-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:h8ph9dm91-python
